# Generated by Django 4.0.3 on 2022-03-17 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cetap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Cetap',
            },
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Modalidad',
            },
        ),
        migrations.CreateModel(
            name='Nivel_Educativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Nivel_Educativo',
            },
        ),
        migrations.CreateModel(
            name='Territorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Territorial',
            },
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel_educativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academica.nivel_educativo')),
            ],
            options={
                'db_table': 'Titulo',
            },
        ),
        migrations.CreateModel(
            name='Egresado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('email_personal', models.EmailField(max_length=50, unique=True)),
                ('email_institucional', models.EmailField(max_length=50, unique=True)),
                ('celular', models.CharField(max_length=10, unique=True)),
                ('fecha_grado', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('cetap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academica.cetap')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academica.modalidad')),
                ('nivel_educativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academica.nivel_educativo')),
                ('territorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academica.territorial')),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academica.titulo')),
            ],
            options={
                'db_table': 'Egresado',
            },
        ),
        migrations.AddField(
            model_name='cetap',
            name='territorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academica.territorial'),
        ),
    ]
